apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: Calculator
  description: An example of a basic math.
  annotations:
    # gitpod.io/host: gitpod.io
    github.com/project-slug: ravalivudutha96/CalculatorApp
spec:
  type: website
  owner: guests
  lifecycle: experimental